controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

joint_state_broadcaster:
  type: joint_state_broadcaster/JointStateBroadcaster

fishbot_diff_drive_controller:
  type: diff_drive_controller/DiffDriveController
  parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    wheel_separation: 0.15
    wheel_radius: 0.033
    odom_frame_id: odom
    base_frame_id: base_link